name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up ARM GCC
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '10-2020-q4'

      - name: Build with make
        run: make
